AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'Gemfile'
Layout/HashAlignment:
  EnforcedColonStyle: table
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/ClassAndModuleChildren:
  EnforcedStyle: compact